title: Catherine Lin
description: UCLA Computer Science Student

url: mscatherinelin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mscatherinelin
   twitter: cath-lin	
   facebook: 
   email: mscatherinelin@gmail.com

google_analytics: "UA-58263416-1"
